// Mocks generated by Mockito 5.4.5 from annotations
// in familynest/test/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:familynest/services/api_service.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> loginUser(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [email, password]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>> registerUser({
    required String? username,
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    String? userRole = 'USER',
    String? photoPath,
    Map<String, dynamic>? demographics,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #username: username,
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #userRole: userRole,
              #photoPath: photoPath,
              #demographics: demographics,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> updateDemographics(
    int? userId,
    Map<String, dynamic>? demographicsData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDemographics, [userId, demographicsData]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getUserById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<int> createFamily(int? userId, String? familyName) =>
      (super.noSuchMethod(
            Invocation.method(#createFamily, [userId, familyName]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> joinFamily(int? userId, int? familyId) =>
      (super.noSuchMethod(
            Invocation.method(#joinFamily, [userId, familyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> postMessage(
    int? userId,
    String? content, {
    String? mediaPath,
    String? mediaType,
    int? familyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMessage,
              [userId, content],
              {
                #mediaPath: mediaPath,
                #mediaType: mediaType,
                #familyId: familyId,
              },
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMessages(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updatePhoto(int? userId, String? photoPath) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoto, [userId, photoPath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getFamilyMembers(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFamilyMembers, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getFamilyMembersByFamilyId(
    int? userId,
    int? familyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFamilyMembersByFamilyId, [userId, familyId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> getFamily(int? familyId) =>
      (super.noSuchMethod(
            Invocation.method(#getFamily, [familyId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> leaveFamily(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveFamily, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> inviteUser(int? userId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#inviteUser, [userId, email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getInvitations() =>
      (super.noSuchMethod(
            Invocation.method(#getInvitations, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> acceptInvitation(int? invitationId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvitation, [invitationId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> rejectInvitation(int? invitationId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectInvitation, [invitationId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getUserFamilies(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFamilies, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getOwnedFamily(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnedFamily, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getJoinedFamilies(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getJoinedFamilies, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> setActiveFamily(int? userId, int? familyId) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveFamily, [userId, familyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getActiveFamily(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveFamily, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getFamilyInvitationsForUser(
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFamilyInvitationsForUser, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> respondToFamilyInvitation(
    int? invitationId,
    bool? accept,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#respondToFamilyInvitation, [
              invitationId,
              accept,
            ]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> inviteUserToFamily(int? userId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#inviteUserToFamily, [userId, email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> updatePhotoWeb(
    int? userId,
    List<int>? bytes,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoWeb, [userId, bytes, fileName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> updateFamilyDetails(
    int? familyId,
    String? familyName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFamilyDetails, [familyId, familyName]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMessagePreferences(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagePreferences, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> updateMessagePreference(
    int? userId,
    int? familyId,
    bool? receiveMessages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessagePreference, [
              userId,
              familyId,
              receiveMessages,
            ]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMemberMessagePreferences(
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberMessagePreferences, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> updateMemberMessagePreference(
    int? userId,
    int? familyId,
    int? memberUserId,
    bool? receiveMessages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemberMessagePreference, [
              userId,
              familyId,
              memberUserId,
              receiveMessages,
            ]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getMessageReactions(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageReactions, [messageId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> addReaction(
    int? messageId,
    String? reactionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [messageId, reactionType]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> removeReaction(int? messageId, String? reactionType) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [messageId, reactionType]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getMessageComments(
    int? messageId, {
    int? page = 0,
    int? size = 20,
    String? sortBy = 'createdAt',
    String? sortDir = 'desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessageComments,
              [messageId],
              {#page: page, #size: size, #sortBy: sortBy, #sortDir: sortDir},
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getCommentReplies(int? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentReplies, [commentId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> addComment(
    int? messageId,
    String? content, {
    int? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [messageId, content],
              {#parentCommentId: parentCommentId},
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> updateComment(
    int? commentId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [commentId, content]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> deleteComment(int? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> markMessageAsViewed(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsViewed, [messageId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getMessageViews(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageViews, [messageId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> isMessageViewed(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#isMessageViewed, [messageId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getMessageEngagementData(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageEngagementData, [messageId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getBatchMessageEngagementData(
    List<int>? messageIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchMessageEngagementData, [messageIds]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
